# 101 文化部展覽資訊

In [1]:
import json
import csv

with open("101.json","r",encoding="utf8") as f:
    fj = json.load(f)


with open("101.csv","w",encoding="utf8") as f:
    fc = csv.writer(f)
    
    for item in fj:
        fc.writerow([item["title"],item["showUnit"],item["startDate"],item["endDate"]])

# 102 新北市公共自行車即時資訊

In [ ]:
import xml.etree.ElementTree as ET
import csv

fx = ET.parse("102.xml")
root = fx.getroot()

fw = open("102.csv", "w", encoding='utf8')
f_csv = csv.writer(fw)

for row in root:
    U = []
    sno = row.find('sno').text  #所回傳的文字內容
    U.append(sno)
    sna = row.find('sna').text
    U.append(sna)
    tot = row.find('tot').text
    U.append(tot)
    f_csv.writerow(U)
fw.close()

# 104 JSON檔案輸出處理

In [ ]:
import json

a={
'people':
[{'id': '1','name': 'Peter','country': 'Taiwan'},
{'id': '2','name': 'Jack','country': 'USA'},
{'id': '3','name': 'Cindy','country': 'Japan'}]}

with open('104.json', 'w') as f:
    json.dump(a, f)

# 201 搜尋字詞

In [15]:
import requests
import re

# 以 requests 模組發出 HTTP GET 請求
sp = requests.get('http://tqc.codejudger.com:3000/target/5201.html')

x = input("請輸入欲搜尋的字串 : ")
y = re.findall(x,sp.text)


if x in sp.text:
    print(x,"搜尋成功")
    print(x,"出現 %d 次" %len(y))

請輸入欲搜尋的字串 : TQC
TQC 搜尋成功
TQC 出現 23 次


# 204 新北市大專院校名單

In [1]:
import requests
import json

url = 'http://tqc.codejudger.com:3000/target/5204.json'
fd = requests.get(url)

x = json.loads(fd.text)

print('新北市大專院校名單：\n')
for i in x:
    if i['type'] == '大專院校':
        print('名稱：%s' % i['name'])
        print('地址：%s' % i['address'])
        print('聯絡電話：%s' % i['tel'])
        print('網站：%s' % i['website'])
        print('資料更新時間：%s' % i['update_date'])
        print()

新北市大專院校名單：

名稱：馬偕醫專三芝校區
地址：新北市三芝區中正路三段42號
聯絡電話：02-26366799
網站：www.mkc.edu.tw
資料更新時間：2018-09-12 06:00:01.0

名稱：馬偕醫學院
地址：新北市三芝區中正路三段46號
聯絡電話：02-26360303
網站：www.mmc.edu.tw
資料更新時間：2018-09-12 06:00:01.0

名稱：法鼓大學
地址：新北市金山區
聯絡電話：
網站：www.ddc.edu.tw/zh-tw
資料更新時間：2018-09-12 06:00:01.0



# 301 產品價格

In [4]:
import pandas as pd

# 資料輸入
datas = [[7500, 6200, 8500, 730000, 60000], [9100, 5300, 5600, 6300000, 65000],
         [7100, 8800, 5100, 690000, 87000], [6900, 5300, 8700, 7400000, 70000]]
indexs_ = ["A", "B", "C", "D"]
columns_ = ["手機", "電腦", "電視", "房子", "車子"]
df = pd.DataFrame(datas, columns = columns_ ,  index = indexs_)

print('行標題為科目，列題標為個人的所有學生成績')
print(df)
print()

# 輸出後二位產品的所有價格
print('後二位的價格')
print(df.tail(2))
print()

# 將房子價格做遞減排序輸出
df1 = df["房子"].sort_values(ascending=False)
print('以房子遞減排序')
print(df1)
print()

行標題為科目，列題標為個人的所有學生成績
     手機    電腦    電視       房子     車子
A  7500  6200  8500   730000  60000
B  9100  5300  5600  6300000  65000
C  7100  8800  5100   690000  87000
D  6900  5300  8700  7400000  70000

後二位的價格
     手機    電腦    電視       房子     車子
C  7100  8800  5100   690000  87000
D  6900  5300  8700  7400000  70000

以房子遞減排序
D    7400000
B    6300000
A     730000
C     690000
Name: 房子, dtype: int64



In [2]:
# 302 矩陣
set_seed = 123

import numpy as np

x = np.random.RandomState(set_seed).randint(low=5, high=16, size=15) #伪随机数生成器：具有类似于随机数的统计特征：https://www.geeksforgeeks.org/random-sampling-in-numpy-randint-function/?ref=rp
print('隨機正整數：', x)

x = x.reshape(3, 5)
print('X矩陣內容：')
print(x)
print('最大：', max(np.ravel(x)))
print('最小：', min(np.ravel(x)))
print('總和：', sum(np.ravel(x)))
print('四個角落元素：')
print(x[np.ix_([0, 2], [0, 4])])

隨機正整數： [ 7  7 11  6  8 15 14 11  6  5  6 14  5  5 14]
X矩陣內容：
[[ 7  7 11  6  8]
 [15 14 11  6  5]
 [ 6 14  5  5 14]]
最大： 15
最小： 5
總和： 134
四個角落元素：
[[ 7  8]
 [ 6 14]]
