DBSCAN群聚演算法：
讀取sklearn.datasets的手寫數字資料集
(1797筆，每筆資料大小8x8 共64個數值特徵欄位)

In [5]:
seed = 0    # 亂數種子數
import numpy as np
from sklearn.datasets import load_digits

# 載入手寫數字資料集
dataset = load_digits()
print(dataset)

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]]), 'target': array([0, 1, 2, ..., 8, 9, 8]), 'frame': None, 'feature_names': ['pixel_0_0', 'pixel_0_1', 'pixel_0_2', 'pixel_0_3', 'pixel_0_4', 'pixel_0_5', 'pixel_0_6', 'pixel_0_7', 'pixel_1_0', 'pixel_1_1', 'pixel_1_2', 'pixel_1_3', 'pixel_1_4', 'pixel_1_5', 'pixel_1_6', 'pixel_1_7', 'pixel_2_0', 'pixel_2_1', 'pixel_2_2', 'pixel_2_3', 'pixel_2_4', 'pixel_2_5', 'pixel_2_6', 'pixel_2_7', 'pixel_3_0', 'pixel_3_1', 'pixel_3_2', 'pixel_3_3', 'pixel_3_4', 'pixel_3_5', 'pixel_3_6', 'pixel_3_7', 'pixel_4_0', 'pixel_4_1', 'pixel_4_2', 'pixel_4_3', 'pixel_4_4', 'pixel_4_5', 'pixel_4_6', 'pixel_4_7', 'pixel_5_0', 'pixel_5_1', 'pixel_5_2', 'pixel_5_3', 'pixel_5_4', 'pixel_5_5', 'pixel_5_6', 'pixel_5_7', 'pixel_6_0', '

In [6]:
X_digits =    dataset.data# 數值特徵
print(X_digits)

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]


In [7]:
y_digits =    dataset.target# 數字類別
print(y_digits)

[0 1 2 ... 8 9 8]


In [ ]:
針對數值欄位標準、建立k-means模型進行分群、計算輪廓係數及準確率.

In [8]:
# 特徵標準化(scale/StandardScaler)
from sklearn.preprocessing import scale
from sklearn.preprocessing import StandardScaler
fd = scale(X_digits)
print(fd)

[[ 0.         -0.33501649 -0.04308102 ... -1.14664746 -0.5056698
  -0.19600752]
 [ 0.         -0.33501649 -1.09493684 ...  0.54856067 -0.5056698
  -0.19600752]
 [ 0.         -0.33501649 -1.09493684 ...  1.56568555  1.6951369
  -0.19600752]
 ...
 [ 0.         -0.33501649 -0.88456568 ... -0.12952258 -0.5056698
  -0.19600752]
 [ 0.         -0.33501649 -0.67419451 ...  0.8876023  -0.5056698
  -0.19600752]
 [ 0.         -0.33501649  1.00877481 ...  0.8876023  -0.26113572
  -0.19600752]]


In [ ]:
分別建立K-Means模型進行分群

In [15]:
# 取出資料集的數字類別數
n_digits = 10

from sklearn.cluster import KMeans
kmean1=KMeans (init='k-means++', n_clusters=n_digits, n_init=10, random_state=seed)
kmean2=KMeans (init='random', n_clusters=n_digits, n_init=10, random_state=seed)

# 利用 PCA 結果建立 K-Means 模型，除以下參數設定外，其餘為預設值
from sklearn.decomposition import PCA
pca= PCA (n_components=n_digits, random_state=seed).fit(fd)
kmean3=KMeans (init=pca.components_, n_clusters=n_digits, n_init=1, random_state=seed)
print(kmean1)
print(kmean2)
print(kmean3)

KMeans(n_clusters=10, random_state=0)
KMeans(init='random', n_clusters=10, random_state=0)
KMeans(init=array([[-0.00000000e+00, -1.82233885e-01, -2.85868337e-01,
        -2.20368329e-01,  2.51717756e-02,  9.49641787e-03,
         5.24749531e-02,  6.26949091e-02, -3.47048698e-02,
        -2.45535873e-01, -2.29151922e-01,  1.07944802e-01,
        -3.62020342e-02, -3.87125429e-02,  8.37788630e-02,
         9.27755563e-02, -1.66987141e-02, -1.36719157e-01,
         6.30507732e-02,  1.22878638e-01, -1.48194794e-01,
         2.3...
        -1.30437556e-01,  7.91432006e-02, -1.52563015e-02,
        -1.48335740e-01,  4.57165550e-02,  4.02893105e-02,
         1.15879591e-01, -1.00764346e-01, -2.40557215e-01,
        -6.32316263e-02, -1.14598893e-01, -1.68445510e-01,
         3.74135442e-02,  2.44130710e-02, -1.36626908e-02,
         7.09502875e-03,  1.30274345e-02, -1.01176066e-01,
        -9.76164558e-02, -3.83552264e-02,  5.44603550e-02,
         2.95498888e-02]]),
       n_clusters=10, n_ini

In [ ]:
計算輪廓係數(Silhouette coefficient)

In [16]:
# 分別計算上述三個 K-Means 模型的輪廓係數(Silhouette coefficient)與
# 分類準確率(accuracy)，除以下參數設定外，其餘為預設值
from sklearn.metrics import silhouette_score
from sklearn.metrics import accuracy_score
lst_name = ['K-Mean (k-means++)', 'K-Means (random)', 'K-Means (PCA-based)']
lst_model = [kmean1,kmean2,kmean3]
for name,model in zip(lst_name,lst_model):
    model.fit(fd)
    name_s = silhouette_score(fd,model.labels_,metric='euclidean')
    
    print('%s:Silhouette=%.4f'%(name,name_s))

K-Mean (k-means++):Silhouette=0.1455
K-Means (random):Silhouette=0.1448
K-Means (PCA-based):Silhouette=0.1388


In [17]:
    print('Accuracy(分類準確率)=%.4f' %accuracy_score (y_digits,model.labels_))

Accuracy(分類準確率)=0.1085
